### ISSUE TITLE
BB2/VW2 Redux compatibility

### ISSUE THREAD

**Issue by CLSoul** [FrostFalcon/FrostsGen5Editor#2]
Is there a way to add compatibility for this editor to BB2/VW2 Redux? I remember PRC working for the original BB2/VW2 mods but for Redux there's nothing

**Comment by FrostFalcon** [comment]
I thought I added compatibility for it a while ago, though maybe it was for the original versions. I don't remember. Is it throwing an error when you load the rom or somewhere else?

**Comment by CLSoul** [comment]
Sleep deprived me should’ve been more specific. 99% of it works perfectly from what I‘ve seen but trying to edit any mon or move that was changed to fairy type shoots me an error about some invalid argument with a value of 17. I would assume because fairy type isn’t defined in your editor?

**Comment by FrostFalcon** [comment]
Open the text editor, go to file (I think) 398 where there's a list of types, and add Fairy to the end of it.
