### ISSUE TITLE
PWT and battle subway

### ISSUE THREAD

**Issue by pablone-lab** [FrostFalcon/FrostsGen5Editor#3]
is there a way to edit the shops of the Battle subway and the PWT? I didn't find it in the Shop Editor section. Btw great work this is the best bw2 editor I have ever seen

**Comment by FrostFalcon** [comment]
There's not currently. I don't know for sure how to go about adding that feature, but if it's what I think it is, the answer would be I can't do it for the foreseeable future. Sorry.

**Comment by pablone-lab** [comment]
ah okay, thanks anyway, keep up with your work
